LANGCHAIN_API_KEY = 'xxxx'
# OPENAI_API_VERSION = 'xxxx'
# deployment_name = 'xxxx'
# AZURE_OPENAI_ENDPOINT = 'xxxx'
# AZURE_OPENAI_API_KEY = 'xxxx'

deployment_name = 'xxxx'
AZURE_OPENAI_ENDPOINT = 'xxxx'
OPENAI_API_VERSION = 'xxxx'
AZURE_OPENAI_API_KEY = 'xxxx'
